### ISSUE TITLE
Change backend from termion to crossterm

### ISSUE THREAD

**Issue by GreasySlug** [kyoheiu/felix#107]
The `termion` does not seem to be well maintained
Also, windows users cannot use `termion` in any environment other than wsl
Since I want to use this in windows, I suggest [crossterm](https://github.com/crossterm-rs/crossterm) as a cross-platform, well-maintained library.
However, this suggestion may not fit your philosophy.

Incidentally, the `crossterm` backend has already been personally implemented.
The migration was easy.
I can make a PR if you want.
(there are some bug)

**Comment by kyoheiu** [comment]
Thank you for pointing this out. The migration makes sense (I don't have Windows environment though, so even if it runs on Windows cannot test it by myself).
At this point, it is somewhat tightly coupled with the code and needs refactoring to avoid introducing new bugs.
If you don't mind, I will try myself to see if crossterm supports this app feature.

**Comment by GreasySlug** [comment]
Thanks for the reply.
I'm still working on fixing the bug, but there is a branch in the repository I forked that I changed to crossterm.
https://github.com/GreasySlug/felix/tree/feature-crossterm
Sorry for the dirty code, but FYI

**Comment by kyoheiu** [comment]
Created my own PR #108 
One thing I noticed is that the color name is different from termion, which should be used in the config file, so this migration will be breaking change.
Or can we use termion color name as is and internally change to crossterm color name?

**Comment by GreasySlug** [comment]
[termion](https://github.com/redox-os/termion/blob/8054e082b01c3f45f89f0db96bc374f1e378deb1/src/color.rs#L62-L77)
```rust
derive_color!("Black.", Black, "0");
derive_color!("Red.", Red, "1");
derive_color!("Green.", Green, "2");
derive_color!("Yellow.", Yellow, "3");
derive_color!("Blue.", Blue, "4");
derive_color!("Magenta.", Magenta, "5");
derive_color!("Cyan.", Cyan, "6");
derive_color!("White.", White, "7");
derive_color!("High-intensity light black.", LightBlack, "8");
derive_color!("High-intensity light red.", LightRed, "9");
derive_color!("High-intensity light green.", LightGreen, "10");
derive_color!("High-intensity light yellow.", LightYellow, "11");
derive_color!("High-intensity light blue.", LightBlue, "12");
derive_color!("High-intensity light magenta.", LightMagenta, "13");
derive_color!("High-intensity light cyan.", LightCyan, "14");
derive_color!("High-intensity light white.", LightWhite, "15");
```

[crossterm](https://github.com/crossterm-rs/crossterm/blob/f845cea5160d7ab60aa7a582f873340078f967fd/src/style/types/color.rs#L124-L142)

```rust
                use Color::*;
                [
                    Black,       // 0
                    DarkRed,     // 1
                    DarkGreen,   // 2
                    DarkYellow,  // 3
                    DarkBlue,    // 4
                    DarkMagenta, // 5
                    DarkCyan,    // 6
                    Grey,        // 7
                    DarkGrey,    // 8
                    Red,         // 9
                    Green,       // 10
                    Yellow,      // 11
                    Blue,        // 12
                    Magenta,     // 13
                    Cyan,        // 14
                    White,       // 15
                ]
```

Internally they are almost the same, just different names.

So, I think it would be fine if we just convert here without changing the config.toml file and config.rs enum.

```rust
            Colorname::Cyan => {
                print_item!(color::Fg(color::Cyan), name, time, selected, self.layout);
            }
```

to

```rust
            Colorname::Cyan=> {
                print_item!(
                    SetForegroundColor(crossColor::DarkCyan),
                    name,
                    time,
                    selected,
                    self.layout
                );
            }

```

**Comment by kyoheiu** [comment]
Seems the migration has completed #108 
Your code (especially `run.rs`) helped me so much! Thank you.
Could you check if this PR works?

**Comment by GreasySlug** [comment]
That's great @kyoheiu.
I can confirm that it works in windows!
I have also already installed `zoxide` and have confirmed that it works as well.

It's a slight bug, but it still uses `canonicalize()`  and It would happen as follows in windows.
```plaintext
 \\?\C:\Users\Slug\Desktop\felix on crossterm
```

**Comment by GreasySlug** [comment]
Also, make_config_if_not_exist() displays non-macos to windows, so please add this as well.
The config file is properly created in the following location.
```rust
        } else if cfg!(target_os = "windows") {
            println!(
                "Default command set as [{}].\nSee ~\\AppData\\Roaming\\felix\\config.toml",
                trimmed
            );
        } else {

```

**Comment by GreasySlug** [comment]
I forgot to mention this too
This is an issue that is issue to windows
`std::fs::File::open(path)` is basically permission denied
I couldn't think of a good workaround for this, so I used whether the metadata was readable or not.

```rust
if cfg!(target_os = "windows") {
    if let Err(e) = std::fs::metadata(&item.file_path) {
        print_warning(e, y);
        screen.flush()?;
        continue;
    }
} else if let Err(e) = std::fs::File::open(&item.file_path) {
    print_warning(e, y);
    screen.flush()?;
    continue;
}
```

**Comment by kyoheiu** [comment]
Thanks for checking. I have fixed the part you mentioned, except for `std::fs::File::open`.
Since this issue is related to the backend migration, I will close it for now and wait for a while to see if there are any bugs.
After merging these changes, if you have other issues (including `File::open`), please create an issue or PR.
