### ISSUE TITLE
Cannot move to child dir cause of permission denied in Windows

### ISSUE THREAD

**Issue by GreasySlug** [kyoheiu/felix#113]
This is an issue specific to windows
In wsl(ubuntu), do not happen.

`std::fs::File::open(path)` is basically not allowed access.

Therefore, using the "l" key is impossible to move to the directory and symbolic link.

**Comment by kyoheiu** [comment]
I don't know whether the problem is with `File::open` or some permissions are screwed up in your environment. Can't find any documentation or comments about `File::open` not working on Windows. Do you see anything?

**Comment by GreasySlug** [comment]
I've searched it, but haven't figured it out yet.
We' ll know that when the crossterm migration is merged and we get feedback from other windows users.
I hope it's just my environment.

**Comment by kyoheiu** [comment]
https://github.com/kyoheiu/felix/issues/75#issuecomment-1279914367
They say `cargo build --target x86_64-pc-windows-gnu` fails, and it's true (on linux). How did you compile on Windows? Could you paste some system information?
