### ISSUE TITLE
Better way to clear active filter

### ISSUE THREAD

**Issue by ok-nick** [kyoheiu/felix#132]
Currently, to clear a filter you must press `/` and then `Backspace`. To me, it doesn't feel very vim-like and it's extremely unergonomic to reach.

I think it would make more sense to just have `Esc` clear an active filter. If a mode is currently selected then it will cancel the mode first, then by pressing `Esc` again, it will cancel the filter.

**Comment by kyoheiu** [comment]
Related #135

**Comment by kyoheiu** [comment]
Now that the filter mode was removed, I'll close this.
