### ISSUE TITLE
Add `<C-d>`, `<C-u>`, `<C-b>`, `<C-f>`, and other navigational mappings

### ISSUE THREAD

**Issue by ok-nick** [kyoheiu/felix#133]
`<C-d>` - Cursor down half screen
`<C-u>` - Cursor up half screen

`<C-b>` - Cursor down screen
`<C-f>` - Cursor up screen

`H` - Cursor top screen
`M` - Cursor middle screen
`L` - Cursor bottom screen

`<C-e>` - Move screen down one line
`<C-y>` - Move screen up one line

`zt` - Align top of screen with cursor
`zz` - Align middle of screen with cursor
`zb` - Align bottom of screen with cursor

**Comment by kyoheiu** [comment]
This app is indeed based on vim-like key mapping, but I have no plans to implement all of vim's spectacular magic. If I ever get frustrated, I will think about these commands.
