### ISSUE TITLE
Change `/` to search w/ `?` like vim

### ISSUE THREAD

**Issue by ok-nick** [kyoheiu/felix#135]
I'm new to `felix` and I'm still getting accustomed to its usual workflow. Although, I've found that filtering isn't always as intuitive as vim-like searching. Sometimes it's easier to just search up or down to the nearest matching filename, rather than filtering every matching filename.

This would be a great feature to add, but it would also be weird if it weren't behind it's vim mapping. Perhaps filtering should be a different keybind and vim searching should be `/` and `?`?

**Comment by kyoheiu** [comment]
Excellent point, thank you.
I am not sure which is more convenient for users, "forward/backward by search keywords" or "filter mode", but the implementation of filter mode seems less sophisticated, so there is room for consideration.

**Comment by kyoheiu** [comment]
@ok-nick  Primitively implemented `/` in #136 , so it would be helpful if you could try this in `feature-search-key` branch.
`?` is not there yet, because `N` after `/{keyword}` is sufficient IMO.

**Comment by ok-nick** [comment]
Is this removing filter mode? I still think filter mode could be useful. I'm not too familiar with file managers but I'd take some pointers from existing ones to see how/if they have this. Perhaps also some more community feedback to see what other people think.

**Comment by kyoheiu** [comment]
Fair enough, Just started Discussion #138 (I'm not sure I can receive any feedback though).

**Comment by kyoheiu** [comment]
#141 merged
