### ISSUE TITLE
Config file creation output is incorrect

### ISSUE THREAD

**Issue by kdb424** [kyoheiu/felix#142]
Output after upgrading to 2.0 from an older version left me with this message
`Config file created. See ~/.config/felix/config.yaml`
This file location is both incorrect, and the extension is now wrong. On Mac, it's `~/Library/Application Support/felix/confix.toml`. This value should probably be dynamic and not set in arbitrary text to prevent these sorts of issues in the future.

**Comment by kyoheiu** [comment]
Thank you for the report. You're right, on my intel mac it showed the path for Unix, though `cfg!(target_os = "mac_os")` was set.
And the process of making config file also had a bug, so fixed it #143

**Comment by kyoheiu** [comment]
Merged #143, you should now see the right path. Could you check it?

**Comment by kyoheiu** [comment]
FYI, from v2.0.0 felix uses yaml, so the extension itself is not wrong.

**Comment by kdb424** [comment]
Confirmed that it's working. Sorry for mixing up which was which on the file extension, that is correct. Only other note I have on this topic is that `~/Library/Application Support/` is normally used for GUI programs on Mac, where as most command line programs like Vim, emacs, ranger, ect use standard Linux file locations even on Mac, so this may be an extra work on your end to handle Mac, while adding to confusion for users. Personally, I'd prefer that the files were in `.config` on Mac as all of my other command line tools are likewise there, but V2.0.1 now is working as you intended at least 👍

**Comment by kyoheiu** [comment]
Excellent! Thank you for checking it out.
Another suggestion, I was not aware of that and will consider it.
