### ISSUE TITLE
Broken patch

### ISSUE THREAD

**Issue by 0323pin** [kyoheiu/felix#144]
Hi, NetBSD maintainer here.
Building 2.0.1 patching `syntect` as you have done here, https://github.com/trishume/syntect/commit/52a19f693eebf2fc0bbfa63a08b03e3aded23a26
fails with

```
error[E0599]: no method named `is_boundary` found for reference `&str` in the current scope
   --> /usr/pkgsrc/wip/felix/work/vendor/syntect-5.0.0/src/util.rs:251:26
    |
251 |         while !rest[0].1.is_boundary(rest_split_index) && rest_split_index > 0 {
    |                          ^^^^^^^^^^^ help: there is an associated function with a similar name: `is_char_boundary`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `syntect` due to previous error
warning: build failed, waiting for other jobs to finish...
```

Replacing `is_boundary` with `is_char_bondary` allows the build to succeed.

Regards

**Comment by kyoheiu** [comment]
Ah, that was kind of typo. After that, I must've fixed it to `is_char_boundary`. Where did you see this code? In my PR or folk, that should be fixed already.
Anyway, this code uses `while`, so this PR https://github.com/trishume/syntect/pull/456 could help you.

**Comment by 0323pin** [comment]
> Where did you see this code? In my PR or folk

The latest commit on your fork, https://github.com/kyoheiu/syntect

Yes, it's fixed. I have the package update ready to merge. Will push it in an hour or so.

**Comment by 0323pin** [comment]
@kyoheiu closing this now.
