### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by kilokon** [kyoheiu/felix#179]
1. Opening a terminal at current directory.
2. Execution of some script in directory. eg "cargo new "
3. command area to be a bit distinct.

**Comment by kyoheiu** [comment]
1. it is difficult to detect which terminal to use (e.g. running `echo $TERM` in wezterm only prints `xterm-256color`). Might be possible to check the running process or add a default terminal name in the config file, but I don't think it is worth it at this time.
2. you can run i.e. `cargo init` with `:cargo init` in felix. Do you want to do something else?
3. I'd be happy if you could give me an example, or the style to use.

**Comment by kyoheiu** [comment]
1. it is difficult to detect which terminal to use (e.g. running echo $TERM in wezterm only prints xterm-256color). Might be possible to check the running process or add a default terminal name in the config file, but I don't think it is worth it at this time.
2. you can run i.e. cargo init with :cargo init in felix. Do you want to do something else?
3. I'd be happy if you could give me an example, or the style to use.

**Comment by kilokon** [comment]
1. $TERM, declared as an env variable just like ` $EDITOR`. I do not know if that could be a possibility, just suggesting.
2. I used to run python scripts off ranger file manager to sort out a messy directory based on file extensions.  
3. Something like `Zathura` maybe took me a little bit of time to find the prompt. 
I'm not a big user of file explorers but this tool is a fun to use.

**Comment by kyoheiu** [comment]
Thanks. For the python script in ranger, I've heard of it but not used yet myself, so I'll check it later.
