### ISSUE TITLE
preview not working with kitty

### ISSUE THREAD

**Issue by salkin-mada** [kyoheiu/felix#181]
`felix` v2.2.4
`chafa` v1.12.4
`imagemagick` v7.1.0.60
`kitty` 0.26.5
Arch Linux 6.1.8

When I press `v` in `felix` the pointer `>` and the bottom "infobar" disappears. An the preview is empty.
![image](https://user-images.githubusercontent.com/12082586/216743544-a75dc3fa-e6fb-4878-a5be-60d9a032c68d.png)
![image](https://user-images.githubusercontent.com/12082586/216743561-1e1be089-8bca-4c05-bcfc-8dafe3f9ce95.png)

`felix` _preview_ works just fine with `alacritty` and `foot` on the same system.

**Comment by kyoheiu** [comment]
Thanks, this was apparently bug.
Fixed by ad5ca5cb679c51491bf611f07556318de8c0ebca
If you'd like to use felix with kitty for now, please `git clone` develop branch and `cargo install --path .` for now.

**Comment by kyoheiu** [comment]
FYI, due to kitty's image drawing structure, felix has to clear and write the entire display for each input if the preview is on, so the user experience is not as good as on other terminals IMO.

**Comment by salkin-mada** [comment]
Yeah `felix` feels way more snappy on `alacritty`. But `chafa` paints preview images way better in `kitty` due to its image capabilities.

**Comment by kyoheiu** [comment]
Wezterm can show detailed image preview, too.

**Comment by salkin-mada** [comment]
ad5ca5c fixed preview on kitty, nice. Thanks!
