### ISSUE TITLE
fx: error while loading shared libraries: libbz2.so.1.0

### ISSUE THREAD

**Issue by rothgar** [kyoheiu/felix#190]
Just letting you know I received this error on fedora 38 beta.

```
fx --version
fx: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory

sudo ln -s /usr/lib64/libbz2.so.1 /usr/lib64/libbz2.so.1.0

fx --version
felix v2.2.5: Up to date.
```

On fedora it's provided by bzip2-libs but there isn't a symlink to that version
```
sudo rpm -ql bzip2-libs
/usr/lib/.build-id
/usr/lib/.build-id/f8
/usr/lib/.build-id/f8/237ff24b622047428b97b1486b393e3a9e38de
/usr/lib64/libbz2.so.1
/usr/lib64/libbz2.so.1.0.8
/usr/share/licenses/bzip2-libs
/usr/share/licenses/bzip2-libs/LICENSE
```

**Comment by kyoheiu** [comment]
Thank you for the report.
Internally felix calls `cargo search felix --limit 1`, so if `fx --version` does not work out of the box, cargo command may also have a problem.

**Comment by kyoheiu** [comment]
Let me figure out: You received that error message only by `fx --version`, or `fx` also output that? If latter, I have to dig into it.

**Comment by rothgar** [comment]
I get the error with both commands. I noticed it first with `fx` and then saw it happens with `fx --version` too. Then I created the symlink to fix it for myself, but thought you'd want to know.

**Comment by kyoheiu** [comment]
Thank you! 
Fedora 38 beta looks pretty new. I'll check it out.

**Comment by rothgar** [comment]
The final release is supposed to come out this week so you shouldn't need to install the beta
