### ISSUE TITLE
felix imported into pkgsrc

### ISSUE THREAD

**Issue by 0323pin** [kyoheiu/felix#20]
FYI, I've packaged and merged `felix` into the pkgsrc main branch, https://mail-index.netbsd.org/pkgsrc-changes/2021/11/14/msg243290.html

The application should become available to NetBSD users through the package manager within a couple of days.

Thanks!
Regards,
pin

**Comment by kyoheiu** [comment]
Thanks!
I'm not familiar with NetBSD, but let me know if you run into problems.

**Comment by 0323pin** [comment]
@kyoheiu Hi, you have taged the latest release as v0,2,9 using commas instead of dots. This causes issues while fetching the source tarball. I'll try to workaround it but, could you please use dots instead of commas, i.e. v0.2.9 instead?

Thanks

**Comment by kyoheiu** [comment]
Sorry, typo.
I fixed the tag to v0.2.9 (by dots). Does this improve the situation?

**Comment by 0323pin** [comment]
@kyoheiu Yes, thanks. Now if finds the tarball and `rustc` finds `Cargo.toml` without any workarounds :)

Thank you. I'll merge the update as soon as I find some time.
