### ISSUE TITLE
feature: migrate to clap (CLI arg parser)

### ISSUE THREAD

**Issue by doprz** [kyoheiu/felix#208]
Hi,

First of all, great project!
I'm curious to hear your thoughts on migrating to [clap](https://github.com/clap-rs/clap) - _A full featured, fast Command Line Argument Parser for Rust_

I've used this crate in the past before and it has been pretty helpful. If you're interested in migrating to it, I think that I can create a PR implementing these changes however I wanted to run this by you first.

**Comment by kyoheiu** [comment]
Thank you for your suggestion.

While `clap` is amazing, I don't see the need to incorporate it into this project. With only two options (-h and -l), I think using `std::env::args` to parse arguments is sufficient.
If you have specific reasons why clap would be a better choice in this code, I'm open to hearing them.
