### ISSUE TITLE
When using PowerShell on Windows, keys are being sent twice.

### ISSUE THREAD

**Issue by kujirahand** [kyoheiu/felix#245]
When using PowerShell on Windows, keys are being sent twice.
The following image shows where I typed ":q" only once.

![felix-bug](https://github.com/kyoheiu/felix/assets/2153829/8a146143-4905-4b1a-abc3-a69c27241986)

**Comment by kyoheiu** [comment]
Thank you for the report.
Possibly related to this crossterm issue: https://github.com/crossterm-rs/crossterm/issues/797
Looks like going to be fixed in the next release.

**Comment by kyoheiu** [comment]
Fixed by c63dc45224f919dcf55304b30e436cfdee041c33
I'd appreciate if you could try this.

**Comment by kyoheiu** [comment]
Fix released in v2.9.0
