### ISSUE TITLE
Enable `Ctrl-h` for Backspace Functionality

### ISSUE THREAD

**Issue by 0x6b** [kyoheiu/felix#252]
Hi there, thank you for the great project. I like it in a snap!

I've noticed that, while executing `z`, `i`, `I`, `c`, and `/`, removing a character backward, the `Ctrl-H` does not work as expected while the backspace key does. I have a strong muscle memory for using `Ctrl-H` as a backspace alternative, this small discrepancy prevents me from using felix smoothly.

I think impact to existing users and complexity the changes will introduce should be minimal. I would be happy to contribute to this enhancement as the changes needed for this looks straightforward. If you agree with this suggestion, I can open a pull request. If not, please just close this issue. Your thoughts and comments would be appreciated. Thanks!

**Comment by kyoheiu** [comment]
Thank you for the suggestion.
Sounds good! I would appreciate if you could make a PR.

**Comment by 0x6b** [comment]
Changed `Ctrl-H` to `Ctrl-h` to reduce ambiguity.
