### ISSUE TITLE
Uppercase letters in keyword search

### ISSUE THREAD

**Issue by lbfalvy** [kyoheiu/felix#259]
Uppercase letters are neither accepted by the keyword search tool nor matched by their lowercase variant. For example, the `~/Pictures` directory isn't found by the search string `/pictures`, and I can't enter the capital P in `/Pictures`.

**Comment by kyoheiu** [comment]
Thank you for the report.
Looks like recent change #254 unexpectedly restricts SHIFT input.
It'd be easy to fix, so please wait...

**Comment by kyoheiu** [comment]
Fixed https://github.com/kyoheiu/felix/pull/260/commits/78a2daa77c50a30cae661ed5dc04121aea441807

**Comment by kyoheiu** [comment]
Released as v2.11.1
I'd appreciate if you could check how this works.

**Comment by lbfalvy** [comment]
It works fine, thank you!
