### ISSUE TITLE
Unable to edit files in a symlinked folder on Windows

### ISSUE THREAD

**Issue by RioNight** [kyoheiu/felix#267]
I am using Windows + Wezterm + bash with the default configuration of `fx`.

Here is the directory in `fx`:
![image](https://github.com/kyoheiu/felix/assets/58403689/3ab0ab41-1aba-4ea6-b598-b557a7b8ae60)

`symlinked-bash` is a symlinked folder. It links to `new-dir`:
![image](https://github.com/kyoheiu/felix/assets/58403689/3abf516b-5da2-4f34-ba52-fbb1ba452af9)
(See the `symlinked-bash -> new-dir`.)
`symlinked-bash` was created in bash using `ln -s new-dir/ symlinked-bash`. Windows Developer Mode had to be enabled and the follwing had to be put in `~/.bashrc`: `export MSYS=winsymlinks:nativestrict`.

`new-dir`:
![image](https://github.com/kyoheiu/felix/assets/58403689/29b5bc9d-6dc3-48f4-a41f-ea94b324c180)

If I press `l` on `symlinked-bash`, the path at the top gets prefixed with `\\?\`. It looks almost like a UNC path:
![image](https://github.com/kyoheiu/felix/assets/58403689/545ea5a2-b635-4b13-8bfe-dd7f35e28cf7)

If I press `l` on `new-dir`, the path at the top is fine:
![image](https://github.com/kyoheiu/felix/assets/58403689/f0d3ffb3-37c2-427a-bbdc-b3e938da3ab9)

If I press `<cr>` on `symlinked-bash`, this occurs. The file is empty and the path at the bottom is messed up.
![image](https://github.com/kyoheiu/felix/assets/58403689/fc99f1fc-7aa3-4a83-ba5d-f12971a0ba32)

If I press `<cr>` on `new-dir`, everything works normally.

**Comment by kyoheiu** [comment]
Thank you for the report.
I hope this is fixed by https://github.com/kyoheiu/felix/commit/04b84264a89b5772abc165142f534d072ddf839d .
The new version will be released soon.

**Comment by kyoheiu** [comment]
Fixed in v2.12.0.
