### ISSUE TITLE
Feature request: Show what a symlink file points to

### ISSUE THREAD

**Issue by RioNight** [kyoheiu/felix#269]
It would be useful to see what a symbolic file points to in fx. It would also help differentiate between normal files and symlink files.

`ls -l` when done in a directory with symlink shows an arrow between a the symlink file and file it links to like so:
![image](https://github.com/kyoheiu/felix/assets/58403689/9ce6c2d6-ebcf-4440-a53f-06220f21bc62)

**Comment by kyoheiu** [comment]
You can distinguish symlink file and normal file by their colors: See `config.yaml`.
Printing the pointed item path might be helpful. I'll think about it.

**Comment by kyoheiu** [comment]
Implemented via #289
