### ISSUE TITLE
[FEATURE REQUEST] Allow case insensitive search

### ISSUE THREAD

**Issue by junnunkarim** [kyoheiu/felix#281]
Currently when searching for `pictures` when directory name is `Pictures`, it is not found.
So would it be possible to kindly implement case insensitive searching?
An config option to turn it on maybe?

**Comment by kyoheiu** [comment]
Thanks for the suggestion.
As you say, setting config option might be enough, just like `ignorecase` in Neovim. I'll work on this.

**Comment by kyoheiu** [comment]
Implemented via #286

**Comment by junnunkarim** [comment]
Tried it out and it works as intended. Thank you!
