### ISSUE TITLE
[BUG] Allow symlink directories to be sorted with normal directories

### ISSUE THREAD

**Issue by junnunkarim** [kyoheiu/felix#282]
Currently symlink directories are not shown with normal directories, they are sorted with files.
I have a symlink directory named `awesome/` and another normal directory named `awesome_yoru/` in my `~/.config/` directory.
When searching for `awesome`, only the `awesome_yoru/` directory is shown at the top and the `awesome/` symlink directory is shown at the bottom with other files.

Would it be possible to fix this issue?

**Comment by kyoheiu** [comment]
Certainly a sort of enhancement. I'll give it a try.

**Comment by kyoheiu** [comment]
Implemented via #287

**Comment by junnunkarim** [comment]
Working perfectly. Thank You!
