### ISSUE TITLE
[Bug] Zoxide cannot handle multiple arguments

### ISSUE THREAD

**Issue by junnunkarim** [kyoheiu/felix#283]
For quick navigation bookmarks are life savers. In `nnn` I used to use them a lot.
I believe many people will be benefited by this feature.
Would you kindly consider adding it?

**Comment by kyoheiu** [comment]
At this moment `zoxide` may work as a kind of bookmarks: For example, you can type `z dot<CR>` to go to `~/dotfiles` directly.
Do you use zoxide integration in felix? And if so, is that not enough?

**Comment by junnunkarim** [comment]
@kyoheiu 

I do use zoxide and I have made `cd` an alias to it.
I also have a `~/dotfiles` directory but it doesn't seem to work on `felix`.
I have tried other combinations but they also don't work, even though they work in my terminal.

But even though I come to make it work, but wouldn't having a dedicated bookmark system be better?
I think having a way to show all my favourite directories with a single keymap or command would be really useful.
What do you think?

**Comment by kyoheiu** [comment]
Sorry, it causes misunderstanding: I mean if you can move to e.g. `~/dotfiles` by `z dot` *in your terminal*, then you can do the same thing in felix (`z dot` to move the directory). It's not restricted to dotfiles directory specifically.

**Comment by junnunkarim** [comment]
Oh sorry, what I was doing previously was that I was going to the command mode and then tried to use `z dot` and it wasn't working. I should have just pressed `z` and typed the directory I wanted to go. It's working great now.

But there seems to be an issue with multiple arguments.
For example if I type `z main dow`, in my terminal it goes to `/mnt/main/main_downloads/` directory but on `felix` it shows `Invalid argument for zoxide.`.
It seems in `felix`, zoxide can't handle more than one argument.

**Comment by kyoheiu** [comment]
Fixed so that `z arg1 arg2<CR>` can work properly.
All recent changes are available in latest `develop` branch: I'd appreciate if you could check how they work.

Other changes:
- Added `ignore_case` option to the config. Just add `ignore_case: true` to the config file and it should work.
- Symlink items linked to directory should appear in the directory section.

**Comment by junnunkarim** [comment]
@kyoheiu 

Thank you very much for your fast work.
Symlink and `ignore_case` is working perfectly.

But issue with zoxide still remains. Now when typing `z main dow` it doesn't show any errors but it goes to the `/mnt/main/` directory, not in `/mnt/main/main_downloads/`.

I have checked your pull request #285 and it seems you have removed the code snippet that checks if the argument count is greater than 2. So now does this [line](https://github.com/kyoheiu/felix/blob/ea4d1d37127bfd1838c6e1a9a92ec0a7136a8472/src/run.rs#L765) only take the 1st argument?

**Comment by junnunkarim** [comment]
Modified the title to better suit the issue at hand.

**Comment by kyoheiu** [comment]
You're right, thanks!
Fixed via #288 .

**Comment by junnunkarim** [comment]
@kyoheiu 
Great!
Everythings working perfectly! Thank you so much!
