### ISSUE TITLE
[ZSH] (eval):1: parse error near `()'

### ISSUE THREAD

**Issue by kirasok** [kyoheiu/felix#296]
- **OS**: ArchLinux
- **Installed with** `pacman`
- **Version**: `v2.13.0`
- **Shell**: Zsh with oh-my-zsh

```
> source <(command felix --init)
(eval):1: defining function based on alias `fx'
(eval):1: parse error near `()'
```

**Comment by kyoheiu** [comment]
Does `felix --init` output lines below?

```
# To be eval'ed in the calling shell
  eval "$(
    if [ -n "$XDG_RUNTIME_DIR" ]; then
      runtime_dir="$XDG_RUNTIME_DIR/felix"
    elif [ -n "$TMPDIR" ]; then
      runtime_dir="$TMPDIR/felix"
    else
      runtime_dir=/tmp/felix
    fi

    mkdir -p "$runtime_dir"

    # Clean up leftover LWD files
    find "$runtime_dir" -type f -and -mmin +1 -delete

    cat << EOF
fx() {
  local RUNTIME_DIR="$runtime_dir"
  SHELL_PID=\$\$ command fx "\$@"

  if [ -f "\$RUNTIME_DIR/\$\$" ]; then
    cd "\$(cat "\$RUNTIME_DIR/\$\$")"
    rm "\$RUNTIME_DIR/\$\$"
  fi
}
EOF
  )"
```

**Comment by kirasok** [comment]
Yes, they are identical
I noticed that it happens when I alias fx=felix​.

When I made symbolic link fx​ in $PATH​ to felix​, shell integration worked

**Comment by kirasok** [comment]
Yes, they are identical

I noticed I get this issue if I alias `fx=felix` before `source`

When I made symbolic link `fx` in to `/usr/bin/felix`, init ran without issue and shell integration worked

**Comment by kyoheiu** [comment]
Glad to hear that. I'll close this.
