### ISSUE TITLE
Couldn't try, fx already aliased 

### ISSUE THREAD

**Issue by zach-is-my-name** [kyoheiu/felix#41]
I was eager to try this but I'm already running a program called fx
https://github.com/antonmedv/fx

**Comment by kyoheiu** [comment]
Ah yes, I thought that might happen...
That's from npm, so you can rename this file manager app binary, which is in ~/.cargo/bin if you install this app from crates.io, to something else (like felix, whatever), and calling it in teminal should work I think (you need to restart your terminal). Could you give it a try?

**Comment by zach-is-my-name** [comment]
Yes that works.
