### ISSUE TITLE
Make deletions fool proof (I'm the fool)

### ISSUE THREAD

**Issue by zach-is-my-name** [kyoheiu/felix#42]
Great job on the app.  I'd just like to request that you make accidentally deleting things a bit more ***fool proof***  

I'm the fool here because I accidentally deleted a folder in my `$HOME` directory 

Luckily... it was `Music`

(I think I hit `dd` if that is in fact the mapping)

**Comment by kyoheiu** [comment]
I care about that surely.
But even if you enter dd, the item just goes to ~/.config/felix/trash so you can retrieve it from there (Real deletion occurs when you enter :empty and y). You think it's not enough?

**Comment by zach-is-my-name** [comment]
Didn't know it had a trash!  And on a personal note thank you for caring... luckily A.) you built the trash function, B.) the folder was empty C.) I don't play my own music (I rely on my surroundings)

**Comment by kyoheiu** [comment]
Glad to hear that!
Yes, surely item delition is sometimes danger. It may be worth to think better solution... thanks.
