### ISSUE TITLE
The name fx is the same as the other utility

### ISSUE THREAD

**Issue by eaglebk** [kyoheiu/felix#46]
In fuchsia - new os of google already has a utility called [fx](https://fuchsia.dev/fuchsia-src/development/build/fx). Will there be no problem with naming the utilities?

**Comment by kyoheiu** [comment]
I do not know about fuchsia much. Is it already ready?
Pretend this app felix can be installed to fuchsia and can work on that, the behavior when you call `fx` in fuchsia (it seems to have a terminal interface) I cannot guess.
Anyway, you can rename binary `fx` of this app (if you install this via `cargo install`, the binary is in `~/.cargo.bin`). See #41

**Comment by eaglebk** [comment]
Fuchsia is still in development. But there are ready assemblies based on it. Thanks for the advice with rename binary.

**Comment by kyoheiu** [comment]
I have heard that fuchsia targets devices like the Google Nest Hub. Interesting if it will be rolled out to desktop and mobile.
Thanks for the info.
