### ISSUE TITLE
Change current path after exit

### ISSUE THREAD

**Issue by kyoheiu** [kyoheiu/felix#49]
#47

**Comment by kyoheiu** [comment]
:q => exit to original
:wq | ZZ => exit to current dir in felix
(behavior of ZZ will change)

**Comment by kyoheiu** [comment]
Nope, it seems impossible or at least hard to implement.

**Comment by emirror-de** [comment]
`xplr` enables this by letting the user decide how to change to the current path by printing the selected working directory to `stdout`. Would this be an option for `felix` as well?

https://github.com/sayanarijit/xplr/blob/e9c868f2464dae5ac97b58b5f6d0b5e1139d2352/src/cli.rs#L19
