### ISSUE TITLE
[Feature Request] Undo/Redo commands

### ISSUE THREAD

**Issue by coastalwhite** [kyoheiu/felix#51]
Similar to the Vim 'u' and 'Ctrl+r' commands, an undo/redo should be possible.

This helps massively when removing or moving files.

**Comment by kyoheiu** [comment]
Thank you for the feedback.
I think it's a little bit difficult to define which commands are the undo/redo targets.
Could you please explain under what circumstances you would like to undo/redo?

**Comment by coastalwhite** [comment]
I would suggest the following commands:
- `dd`
- `d`
- `p`
- `:mv`
- `:cp`
- `:rm`

Of course, this would almost making an exception for the `mv`, `cp` and `rm` commands (on GNU). This would complicate OS interoperability and could massively add complexity.

Maybe it is just easier to add keybindings for *moving* selected files and only add undo and redo to the `dd`, `d`, `p`, `m` (move) commands. This would actually be more logical to me and then the `:...` commands are seen as a *"raw"* mode.

That is just my two cents. I am curious what you would say about that.

**Comment by kyoheiu** [comment]
Fair point!
`dd / d`, `p`, and `c` are completely processed in felix, so the save/revert of these processes can be handled inside the app. (BTW, changes made by `:` (shell mode), such as `:rm some.file` for example, are in a sense external and should not be reverted by felix I think.)

I'll give this a try. Thank you!

**Comment by kyoheiu** [comment]
undo/redo implemented 26d8aa1a8cfe9087be7a035ed875c65905e00c82
