### ISSUE TITLE
[Feature Request] In manager file previews like Ranger or Vifm?

### ISSUE THREAD

**Issue by GNOMES** [kyoheiu/felix#53]
Are there plans to support in manager file previews like Ranger or Vifm that let you see file contents on the side?

**Comment by kyoheiu** [comment]
Thank you for the request.  
I have no plans to do that, I'd like to keep this app's feel and look as simple as possible.

**Comment by kyoheiu** [comment]
Added preview feature in v0.9.0 #62 . Will soon publish to crates.io and AUR. Again thank you for the request and inspiring me!
