### ISSUE TITLE
Add to Homebrew for Mac users

### ISSUE THREAD

**Issue by GNOMES** [kyoheiu/felix#63]
Please consider adding your application to Homebrew so it can easily be found/install on MacOS 
https://docs.brew.sh/Adding-Software-to-Homebrew

**Comment by kyoheiu** [comment]
Thank you for the request.
I'm not familiar with macOS package managers, so will do some digging.

**Comment by kdb424** [comment]
https://federicoterzi.com/blog/how-to-publish-your-rust-project-on-homebrew/

Was tempted to help by creating the package, but didn't want to take ownership from you. It's pretty simple coming from the AUR, which I see is supported.

**Comment by kyoheiu** [comment]
Note: `~/,config` directory may be an option.
